### ISSUE TITLE
error line 6

### ISSUE THREAD

**Issue by borisBelloc** [karthikeyankc/swoopy#3]
hello,

when launching your script, i got this error : 

>   File "g:\Google Drive\pw.py", line 6
>     data_path = os.path.expanduser('~') + "\AppData\Local\Google\Chrome\User Data\Default"
>                                          ^
> SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 28-29: truncated \UXXXXXXXX escape

any idea ?
(using windows 10 and python 3.x)

**Comment by karthikeyankc** [comment]
Yeah. The single backslash followed by 'U' is a Unicode escape `\U`. You can pass the `data_path` string as a raw string by adding an `r` at the beginning or using double backslashes. Or try using forward slashes instead of backslashes. More information [here](https://docs.python.org/2/reference/lexical_analysis.html#literals).

**Comment by borisBelloc** [comment]
thank you for tips.
